version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Bundler version
          command: bundle -v
      - run:
          name: Update bundle
          command: bundle update --bundler
      - ruby/bundle-install
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer test
          command: |
            bundle exec htmlproofer _site \
            --check-html \
            --enforce-https \
            --report-invalid-tags \
            --report-eof-tags \
            --report-mismatched-tags \
            --http_status_ignore 403,999